const data1 = {
  amount: 6.027456183070403,
  submitDate: '2000-01-23T04:56:07.000+00:00',
  bookingDate: '2000-01-23T04:56:07.000+00:00',
  availability: {
    date: '2000-01-23',
    availablityId: 0,
    catalogue: {
      venue: 'venue',
      catalogueId: 0,
      address: 'address',
      city: 'city',
      rateUnit: 'Minute',
      remark: 'remark',
      provider: {
        firstName: 'firstName',
        lastName: 'lastName',
        userStatus: 5,
        phone: 'phone',
        userId: '1',
        email: 'email',
        username: 'username',
      },
      rate: 5.637376656633329,
      terms: 'terms',
      name: 'NUS ISS Meeting Room#5',
      currency: 'SGD',
      tag: [
        {
          tagId: 6,
          descritpion: 'descritpion',
          status: 'Active',
        },
        {
          tagId: 6,
          descritpion: 'descritpion',
          status: 'Active',
        },
      ],
      status: 'Open',
    },
  },
  paymentDate: '2000-01-23T04:56:07.000+00:00',
  complete: false,
  user: {
    firstName: 'firstName',
    lastName: 'lastName',
    userStatus: 5,
    phone: 'phone',
    userId: '1',
    email: 'email',
    username: 'username',
  },
  bookingId: 0,
  catalogue: {
    venue: 'venue',
    catalogueId: 0,
    address: 'address',
    city: 'city',
    rateUnit: 'Minute',
    remark: 'remark',
    provider: {
      firstName: 'firstName',
      lastName: 'lastName',
      userStatus: 5,
      phone: 'phone',
      userId: '1',
      email: 'email',
      username: 'username',
    },
    rate: 5.637376656633329,
    terms: 'terms',
    name: 'NUS ISS Meeting Room#5',
    currency: 'SGD',
    tag: [
      {
        tagId: 6,
        descritpion: 'descritpion',
        status: 'Active',
      },
      {
        tagId: 6,
        descritpion: 'descritpion',
        status: 'Active',
      },
    ],
    status: 'Open',
  },
  createDate: '2000-01-23T04:56:07.000+00:00',
  status: 'New',
}

module.exports = {
  data1,
}
