export const NAV_UPDATE_CURRENT_LOCATION = 'NAV_UPDATE_CURRENT_LOCATION'
export const BOOKING_UPDATE_BOOKING_LIST = 'BOOKING_UPDATE_BOOKING_LIST'
export const CATALOGUE_UPDATE_CATALOGUE_LIST = 'CATALOGUE_UPDATE_CATALOGUE_LIST'
