export default (theme: any) => ({
  root: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    height: 'calc(100% - 90px)',
    backgroundColor: theme.color.primaryLight,
    padding: '40px 0px 50px 0px',
  },
  searchSection: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: 70,
    backgroundColor: 'white',
    boxShadow: '0px 3px 6px lightgrey',
  },
  searchSectionTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-even',
    height: 35,
    padding: '5px 5px 0px 5px',
    // marginTop: 5,
  },
  searchBar: {
    height: 24,
    width: 'calc(100% - 90px)',
    padding: 2,
    border: '1px solid lightgrey',
    borderRadius: 5,
  },
  qrScanner: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: '1px solid lightgrey',
    borderRadius: 5,
    height: 24,
    width: 90,
    marginLeft: 5,
    padding: 2,
  },
  searchSectionBottom: {
    display: 'flex',
    alignItems: 'center',
    minWidth: '100%',
    height: 35,
    overflowX: 'hidden',
    overflowY: 'hidden',
  },
  scrollContainer: {
    display: 'flex',
    alignItems: 'center',
    height: 55,
    margin: '5px 0px 5px 0px',
    overflowX: 'scroll',
    overflowY: 'hidden',
  },
  filterSelector: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 15,
    padding: 5,
    borderRadius: 5,
    backgroundColor: theme.color.primary,
    fontSize: 12,
    marginRight: 5,
    '&:first-child': {
      marginLeft: 5,
    },
    '&:nth-last-child(2)': {
      marginRight: 0,
    },
  },
  filterText: {
    whiteSpace: 'nowrap',
    marginRight: 5,
  },
  filterSelectorRightFill: {
    width: 5,
    minWidth: 5,
  },
  listings: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: 'calc(var(--vh, 1vh) * 100 - 160px)',
    width: 'calc(100% - 16px)',
    overflowY: 'scroll',
  },
  listing: {
    display: 'flex',
    flexDirection: 'column',
    width: 'calc(100% - 16px)',
    backgroundColor: 'white',
    margin: '5px 0px',
    boxShadow: '0px 3px 6px lightgrey',
    padding: 5,
  },
  listingRow1: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: 'lightgrey',
    fontSize: 12,
  },
  listingRow2: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 18,
  },
  listingRow3: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: 'grey',
    fontSize: 12,
  },
  tags: {
    display: 'flex',
    flexDirection: 'row',
  },
  tag: {
    paddingLeft: 3,
  },
})
